name: groupoids
version: 1.66
date: 2019-05-29
description: |
    Calculations with finite groupoids and their homomorphisms

authors:
    - name: Emma J. Moore
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

maintainers:
    - name: Christopher D. Wensley
      url: http://pages.bangor.ac.uk/~mas023/

GAP: ">=4.10.1"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2019.02.22"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "GAPDoc"
      version: ">= 1.6.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "fga"
      version: ">= 1.4.0"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"

suggested-pkgs:
    - name: "semigroups"
      version: ">= 3.1.1"
      url: "https://gap-packages.github.io/Semigroups"

www: https://gap-packages.github.io/groupoids/
readme: README.md
packageinfo: https://gap-packages.github.io/groupoids/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/groupoids/releases/download/v1.66/groupoids-1.66.tar.gz

abstract: |
    The groupoids package provides a collection of functions for computing with finite groupoids, graph of groups, and graphs of groupoids. These are based on the more basic structures of magmas with objects and their mappings. It provides functions for normal forms of elements in Free Products with Amalgamation and in HNN extensions. Up until April 2017 this package was named Gpd.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
